# Generated by Django 6.0.1 on 2026-01-30 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customerDB',
            fields=[
                ('OderID', models.IntegerField(primary_key=True, serialize=False)),
                ('C_Name', models.CharField(max_length=25)),
                ('Address', models.CharField(max_length=60)),
                ('Mobile_No', models.IntegerField()),
                ('Amount', models.FloatField()),
                ('Item_Name', models.CharField(max_length=100)),
                ('Oder_Cancellation', models.CharField(max_length=20)),
            ],
        ),
    ]
